#!/bin/sh

if [ -z "$1" ];
	then
		echo "No options found, aborting."
		echo 'Usage: create_usb usb_device [XX:XX:XX:XX:XX:XX]'
		echo 'eg.   "create_usb /dev/sdd 11:22:44:33:AD:AD" '
		exit 1
	else
		if [ ! -b $1"1" ]; then
			echo $1" is not a block device or "$1"1 partition does not exist."
			echo 'Usage: create_usb usb_device [XX:XX:XX:XX:XX:XX]'
			echo 'eg. "create_usb /dev/sdd 11:22:44:33:AD:AD" '
			exit 1
		fi
fi

mkdir -p /tmp/mnt
umount $1"1" > /dev/null 2>&1
mount $1"1" /tmp/mnt > /dev/null 2>&1

if [ $(echo $?) -ne 0 ]; then
	echo $1"1 partition needs to have a filesystem."
	echo "Cannot mount "$1"1, aborting."
	exit 1
fi

echo;echo;echo '*****************************************************'
echo "Will now write files to "$1"1!"
echo $1"1 WILL BE WIPED!!!"
sleep 5
rm -rf /tmp/mnt > /dev/null 2>&1
\cp -rp ./content/* /tmp/mnt/ > /dev/null 2>&1
echo; echo; sleep 2
chmod +x /tmp/mnt/usb_key_func.sh.2
chmod +x /tmp/mnt/nsa310_fw/usb_key_func.sh


if [ -z "$2" ];
	then
		echo 'No MAC address given. Keeping 00:19:CB:00:51:81'
		sleep 5
	else
		if [ $(echo $2 | egrep "^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$") ];
			then
				sed -i "s/mrd_mac 00 19 CB 00 51 81/mrd_mac $(echo $2 | sed -e 's/:/ /g')/" /tmp/mnt/usb_key_func.sh.2
				echo "Changed MAC address in usb_key_func.sh.2 to "$2
			else
				echo "Invalid MAC "$2" given. Keeping 00:19:CB:00:51:81"
				sleep 5
		fi
fi

echo "Done. Syncing USB drive..."
sync

umount $1"1"
echo; echo; echo;
echo "You can now remove the usb stick."