#!/bin/sh

if [ echo $1 | egrep "^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$" ];
	then
		sed -ie "s/mrd_mac 00 19 CB 00 51 81/mrd_mac $(echo $1 | sed -e 's/:/ /g')/" ./nsa310_fw/usb_key_func.sh.2
		exit 0
	else
		echo 'Usage: set_mac_address xx:xx:xx:xx:xx:xx'
		echo ''
		echo 'Invalid MAC address input. Exiting...'
		exit 1
fi

